on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3

      - name: Publish package distributions to PyPI
        run: pdm publish
        
  send-discord-notification:
    name: Discord notification
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    uses: Ilshidur/action-discord@master
    with:
      args: 'The project etl-pipeline-runner has been published to pypi (https://pypi.org/project/etl-pipeline-runner/).'
