on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3

      - name: Publish package distributions to PyPI
        run: pdm publish

  send-discord-notification:
    name: Discord notification
    uses: appleboy/discord-action@master
    with:
      webhook_id: ${{ secrets.DISCORD_WEBHOOK_TOKEN_ID }}
      webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      args: etl-pipeline-runner has been published to pypi.
