on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3

      - name: Publish package distributions to PyPI
        run: pdm publish

  send-discord-notification:
    needs: [pypi-publish]
    name: send discord notification
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/discord-action@master
    - name: Discord notification
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_TOKEN_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#48f442"
        message: etl-pipeline-runner has been published to pypi.
