on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.11']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "credentials.json"
          json: ${{ secrets.MY_JSON }}
        
      - uses: actions/checkout@v3
      
      - name: Set up PDM
        id: setup-pdm
        needs: [create-json]
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-dependencies
        needs: [setup-pdm]
        run: |
          pdm sync -d -G testing
      - name: Run Tests
        needs: [install-dependencies]
        run: |
          pdm run -v pytest tests
